# Generated by Django 4.1.4 on 2023-04-25 08:03

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='TITLE')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
        ),
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/authors/8.jpg', upload_to='post/', verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('body', models.TextField()),
                ('commentNum', models.IntegerField(default=0, verbose_name='commentaryalar soni')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('massage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='subject')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/authors/8.jpg', upload_to='post/', verbose_name='rasm')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='date')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='mavzu')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/', verbose_name='Rasm')),
                ('oyinNomi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('date', models.DateField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name=accounts.models.CustomUser)),
                ('yuklashlarSoni', models.IntegerField(blank=True, null=True, verbose_name='yuklab olinganlar soni')),
                ('like', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='LIke')),
                ('ball', models.SmallIntegerField(blank=True, null=True, verbose_name='Ball')),
                ('ortachaBal', models.SmallIntegerField(blank=True, null=True, verbose_name='Urtacha ball')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Kurganlar')),
                ('version', models.FloatField(blank=True, null=True, verbose_name='Version')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('comentNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.comentary')),
            ],
        ),
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/', verbose_name='Rasm')),
                ('startDate', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('endDate', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('timesNum', models.SmallIntegerField(blank=True, null=True, verbose_name='timelar soni')),
                ('participants_age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age')),
                ('turnirhomiysi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Homiy')),
                ('groupNum', models.SmallIntegerField(blank=True, null=True, verbose_name='group num')),
                ('priz1', models.CharField(blank=True, max_length=50, null=True, verbose_name='1-urin')),
                ('priz2', models.CharField(blank=True, max_length=50, null=True, verbose_name='2-urin')),
                ('priz3', models.CharField(blank=True, max_length=50, null=True, verbose_name='3-urin')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oyinNomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/', verbose_name='profil rasmi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
