# Generated by Django 4.1.4 on 2023-04-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profil_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnir',
            old_name='name',
            new_name='user',
        ),
    ]
