# Generated by Django 4.1.4 on 2023-05-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profil'),
        ),
    ]
