# Generated by Django 4.1.4 on 2023-05-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_contact_id_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.profil'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
